AllCops:
  Exclude:
    - '**/Gemfile*'
    - '**/*.gemspec'
    - 'bin/*'
  TargetRubyVersion: 2.6
Layout/LineLength:
  Max: 120
Metrics/ClassLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/Documentation:
  Enabled: false
